### ISSUE TITLE
Any chance of publishing an entire Unity project?

### ISSUE THREAD

**Issue by andybak** [demonixis/SSGI-URP#1]
I haven't managed to get it to work so far.

Now - I'm happy to suss that out on my own but in my experience anything moderately complex like this that is published without a working example project (i.e. the actual Unity project dir in it's entirely with Packages and ProjectSettings directories) has only a 50/50 chance of working. There's too many potential things to overlook or version issues to deal with. This probability also diminishes over time ;-)

A working project gives one an existence proof that the thing works and a way to work backwards setting by setting to get things working in one's own project.

**Comment by demonixis** [comment]
Hello, you can put everything in a project and it'll work. You just have to configure your Renderer or use the URP Asset of the repo. 

This structure is required to make it a package for Package Manager.

**Comment by andybak** [comment]
Yep. I understand that. But I think you overlooked the point I was trying to make.

I've read the readme and followed the instructions but for some reason it's not working.

Rather than ask you for help in fixing it, a sample project would allow me to solve it myself.

**Comment by andybak** [comment]
Don't worry. I did solve it in the end. I made a mistake about the version of URP.

I still think sample projects are useful. Keijiro's model is a good one to follow - master branch is a full project and there's a branch for the URP package.

**Comment by demonixis** [comment]
OK thanks for the tip ;)

**Comment by andybak** [comment]
(Just for anyone else reading this - fixing the package version didn't work. I've got the right versions, the right URP settings as far as I can tell. However viewing the demo scene and toggling "enabled" makes no difference.)
